In [1]:
import numpy as np

In [4]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[3]

3

In [8]:
arr[1:7] #slicing

array([1, 2, 3, 4, 5, 6])

In [9]:
arr[:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [11]:
arr[0:3] = 50

In [12]:
arr

array([50, 50, 50,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr = np.arange(0,11)

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
slice_of_arr = arr[0:6]

In [16]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [17]:
slice_of_arr[:] = 99

In [18]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [19]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [20]:
arr_copy = arr.copy()  #moving array to another array 

In [21]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [24]:
arr_copy[:] = 100

In [25]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [26]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [27]:
#indexing a 2d array 

In [28]:
arr_2d = np.array([[1,2],[3,4]])

In [29]:
arr_2d

array([[1, 2],
       [3, 4]])

In [33]:
arr_2d[1]#row 1

array([3, 4])

In [34]:
arr_2d[0]#row0

array([1, 2])

In [35]:
arr_2d[1][0]

3

In [36]:
arr_2d[1,0]

3

In [38]:
arr_2d[:]

array([[1, 2],
       [3, 4]])

In [39]:
arr_2d[0,:]

array([1, 2])

In [41]:
arr_2d[:,1]

array([2, 4])

In [42]:
arr_2d1 = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [43]:
arr_2d1

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [82]:
arr_2d1[1:3,1:2]

array([[25],
       [40]])

In [81]:
arr_2d1[1:3,1:2][0]

array([25])

In [ ]:
#conditional selection 

In [83]:
arr = np.arange(1,11)

In [84]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
bool_arr = arr > 5  #array of boolean values

In [87]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [88]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [89]:
arr[arr<5]

array([1, 2, 3, 4])

In [93]:
arr[arr>=0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
arr_2d = np.arange(50).reshape(5,10)

In [95]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [99]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])